### ISSUE TITLE
Fails to kustomize build when helmCharts is part of kustomization.yaml: must specify --enable-helm

### ISSUE THREAD

**Issue by HariSekhon** [kubevious/cli#15]
Hi,

How do I ensure that the `kustomize build` command that kubevious CLI calls specifies the `--enable-helm` switch so that the manifest generation can occur?

Without it I get errors like this for a lot of my repo:

```
      ❌ ☸️  KUSTOMIZE: /Users/hari/github/k8s/keycloak/base
         � Failed to extract manifest from kustomize. Reason: Command failed: kustomize build /Users/hari/github/k8s/keycloak/base -o /var/folders/18/zv7bm4b55cj500q22s15lygh0000gn/T/tmp-35294-wFLWJiyfm6xe
         Error: trouble configuring builtin HelmChartInflationGenerator with config: `
         includeCRDs: true
         name: keycloak
         namespace: keycloak
         releaseName: keycloak
         repo: https://charts.bitnami.com/bitnami
         valuesFile: values.yaml
         version: 14.2.0
         `: must specify --enable-helm
```

You can reproduce this easily by doing:

```shell

git clone https://github.com/HariSekhon/Kubernetes-configs k8s

cd k8s

kubevious guard keycloak
```

Thanks

Hari

**Comment by rubenhak** [comment]
Hi @HariSekhon, thanks for submitting this issue.
Please try it out with with Kubevious CLI v1.0.56. No need to add the new flags, it will figure out on its on when there is a need to use that flag. It will take a couple of days for the new version to be available on brew, but you can try using the binaries, docker image, github action, or the npm:
```
$ npm install kubevious -g
```

**Comment by HariSekhon** [comment]
The latest release does indeed solve it, thanks!
