### ISSUE TITLE
Pre-commit is really slow

### ISSUE THREAD

**Issue by kinoute** [kubevious/cli#16]
Hello,

First, thanks for this great CLI! We are trying to use it as a pre-commit to avoid spending too much time in CI jobs with failed deployments due to a misconfiguration of our manifests.

Unfortunately, the pre-commit hook is really slow compared to the use of the `kubevious` CLI directly. When using the CLI, it takes a few seconds:

```bash
$ time kubevious lint kustomize/

-= SUMMARY =-
    📚 Sources: 40
        ✖️  Sources with Errors: 0
    📄 Manifests: 141
        ✅ Valid Manifests: 141
        ✖️  Manifests with Errors: 0
        ❕ Manifests with Warnings: 0

kubevious lint kustomize/  7,06s user 0,49s system 129% cpu 5,838 total
```

But with pre-commit, it gets way worse:

```yaml
  - repo: https://github.com/kubevious/cli
    rev: v1.0.58
    hooks:
      - id: kubevious-lint
        args: ["lint", "kustomize/"]
```

```bash
Kubevious Lint checking for manifest API validity........................Passed
- hook id: kubevious-lint
- duration: 68.92s

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
- Identifying manifest sources...
[...]
-= SUMMARY =-
    📚 Sources: 40
        ✖️  Sources with Errors: 0
    📄 Manifests: 141
        ✅ Valid Manifests: 141
        ✖️  Manifests with Errors: 0
        ❕ Manifests with Warnings: 0
```

Any ideas to speed this up? It kinda slows down our development workflow at the moment.

Thanks!

**Comment by rubenhak** [comment]
hi @kinoute, thanks for using Kubevious!
It is a little bit hard to guess. Can you try to run the "kubevious lint" manually using a docker image first?

try running it like this:
```sh
docker run --rm -v ${PWD}:/src kubevious/cli lint /src
```

**Comment by kinoute** [comment]
After the initial run where it downloaded the image I re-run the command, it took 22 seconds:

```bash
 time docker run --rm -v ${PWD}:/src kubevious/cli lint kustomize/
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
- Identifying manifest sources...
✔ Sources identified.
- Loading manifests...
- Executing kustomize build /src/kustomize/base -o /tmp/tmp-8-wZ7VQX1l04w3
✔ Succeeded: kustomize build /src/kustomize/base -o /tmp/tmp-8-wZ7VQX1l04w3
- Executing kustomize build /src/kustomize/dev -o /tmp/tmp-8-sh8yo6RyjL6S
✔ Succeeded: kustomize build /src/kustomize/dev -o /tmp/tmp-8-sh8yo6RyjL6S
- Executing kustomize build /src/kustomize/master -o /tmp/tmp-8-5mRZEP8vFyTS
✔ Succeeded: kustomize build /src/kustomize/master -o /tmp/tmp-8-5mRZEP8vFyTS
- Executing kustomize build /src/kustomize/preprod -o /tmp/tmp-8-kjq5x0HoQMwF
✔ Succeeded: kustomize build /src/kustomize/preprod -o /tmp/tmp-8-kjq5x0HoQMwF
✔ Manifests loaded.
- Loading K8s API Schema...
✔ Fetched K8s API schema.
- Linting manifests...
✔ Lint complete.
ℹ️  Linting against Kubernetes Version: 1.25.2

-= SOURCES =-
   ✅ No issues with sources.

-= MANIFESTS =-
   ✅ No issues with manifests.

-= SUMMARY =-
    📚 Sources: 12
        ✖️  Sources with Errors: 0
    📄 Manifests: 16
        ✅ Valid Manifests: 16
        ✖️  Manifests with Errors: 0
        ❕ Manifests with Warnings: 0

ℹ️  Run with --detailed to see all sources and manifests

✅ Lint Succeeded.
docker run --rm -v ${PWD}:/src kubevious/cli lint kustomize/  0,04s user 0,02s system 0% cpu 22,354 total
```

The script was stuck on the line `- Linting manifests...` for more than 7/8 seconds if this can help. Tree of the kustomize folder:

```bash
kustomize/
├── base
│   ├── job-populate.yaml
│   ├── job-database.yaml
│   ├── job-messages.yaml
│   └── kustomization.yaml
├── dev
│   ├── job-populate.yaml
│   ├── job-database.yaml
│   ├── job-messages.yaml
│   └── kustomization.yaml
├── master
│   ├── job-populate.yaml
│   ├── job-database.yaml
│   ├── job-messages.yaml
│   └── kustomization.yaml
└── preprod
    ├── job-populate.yaml
    ├── job-database.yaml
    ├── job-messages.yaml
    └── kustomization.yaml
```

Nothing fancy. Running macOS Ventura 13.6, Docker 4.24.0.

**Comment by rubenhak** [comment]
Can you run with logs on:
```
docker run --rm -v ${PWD}:/src -e LOG_LEVEL=debug  kubevious/cli lint kustomize/
```

**Comment by kinoute** [comment]
Here is the full log: https://gist.github.com/kinoute/7e92693042eb62d13d2de2dd7dc27a62

**Comment by kinoute** [comment]
I just saw you tried to add ARM64 build to the repo. I think this is a good thing. I made two changes in my Docker setup:

- First I allowed Docker to use Rosetta to run AMD64 images, which made kubevious CLI AMD64 image/container run in 6 seconds for the same folder.
- Then I cloned your repo and built an ARM64 image of the CLI to test it out. It runs in 3.7 seconds.

```
docker run --rm -v ${PWD}:/src -e LOG_LEVEL=debug kubevious-test lint   0,04s user 0,03s system 1% cpu 3,799 total
```

**Comment by rubenhak** [comment]
I'll try to update you next weekend. There are some complications with arm64 builds in the CI pipeline. There is definitely space for improvement, but much of those 3.7 seconds goes into the baseline, regardless if there are 8 manifests or 80. 

Are you also using "guard" command or only "lint" ?

**Comment by kinoute** [comment]
I use "lint" in both situations: in my pre-commit hooks and in my CI/CD job.

**Comment by rubenhak** [comment]
@kinoute, can you give it a try with v1.0.60? The image is now build for both platforms: [https://hub.docker.com/layers/kubevious/cli/1.0.60/images/sha256-03f6e476f36ddb542a576cc54ce03d143d61afcc8003ee1f74182ae7b8ea055a?context=repo](https://hub.docker.com/layers/kubevious/cli/1.0.60/images/sha256-03f6e476f36ddb542a576cc54ce03d143d61afcc8003ee1f74182ae7b8ea055a?context=repo)

**Comment by kinoute** [comment]
@rubenhak Looks way better, thank you!
