### ISSUE TITLE
Upgrade kustomize to 5.1 in kubevious CLI Docker image

### ISSUE THREAD

**Issue by renaudguerin** [kubevious/cli#17]
Hi,

We use the public Kubevious CLI Docker image in our CI, and we just ran into [this Kustomize bug](https://github.com/kubernetes-sigs/kustomize/issues/4841#issuecomment-1341260418) during validation, which we didn't get when running `kustomize build` during development.

The reason is that the latest kubevious Docker image includes Kustomize 4.5.7. The bug [has been fixed in Kustomize 5.1.0](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.1.0). The fix does change Kustomize behaviour and can introduce backward incompatibilities.

Could you please release a new Docker image with the latest Kustomize ? Maybe with a warning for existing users (who shouldn't be using `latest` anyway ;) )

**Comment by rubenhak** [comment]
hey @renaudguerin, I'll look at this over the weekend. There are a few other "image" related activities to take care of.

**Comment by renaudguerin** [comment]
Hi @rubenhak 
Thanks for this, just checking if you have a new ETA so we can plan a workaround ?

**Comment by rubenhak** [comment]
@renaudguerin, can you give it a try with v1.0.60?

**Comment by renaudguerin** [comment]
> @renaudguerin, can you give it a try with v1.0.60?

Yes that fixed this issue, thanks !
I've just opened another one : #18

**Comment by rubenhak** [comment]
Thanks for verifying. Closing the issue.
